export enum ComplaintStatus {
    PENDING = 'PENDING',
    RESOLVED = 'RESOLVED',
    IN_PROGRESS = 'IN_PROGRESS'
}
  
export interface Complaint {
    id: string;
    content: string;
    timestamp: number;
    status: ComplaintStatus;
    category?: string; // Auto-generated by Fast AI
    aiAnalysis?: string; // Generated by Thinking Model
    transcription?: string; // If audio was used
    isAudio: boolean;
}

export interface ChatMessage {
    id: string;
    role: 'user' | 'model';
    text: string;
}

export enum ViewMode {
    STUDENT = 'STUDENT',
    ADMIN = 'ADMIN'
}

export interface AdminProfile {
    name: string;
    role: string;
    department: string;
}